spring:
  profiles.active: local
  application.name: infinvis-account-service
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public